apiVersion: v1
kind: Pod
metadata:
  name: nodejs-liveness-demo
  labels:
    app: nodejs-liveness
spec:
  containers:
  - name: nodeapp
    image: 088042034872.dkr.ecr.us-east-1.amazonaws.com/nodeapp
    ports:
      - containerPort: 3000
    livenessProbe:
      httpGet:
        path: /healthz
        port: 3000
      initialDelaySeconds: 5
      periodSeconds: 10
      failureThreshold: 3
