apiVersion: v1
kind: Pod
metadata:
  name: aws-cli-pod
spec:
  serviceAccountName: s3-access-sa
  containers:
    - name: aws-cli
      image: amazonlinux:2
      command: [ "sleep", "3600" ]  # Keep pod running
      tty: true
